### ISSUE TITLE
Missing status when status change

### ISSUE THREAD

**Issue by lcdhead** [DiscordStyles/SimplyDark#5]
In the last cosmetic/logo change update, it appears they changed how statuses work, and now when someone changes their status, it appears blank until refreshing. Here i have an example shown:

![M0soKp1](https://user-images.githubusercontent.com/84220589/118350420-133c7700-b546-11eb-801d-677b7e45d5dd.gif)

all help would be appreciated, as it is rather distracting.

**Comment by lcdhead** [comment]
could you maybe not close this without explaining why this is happening or whether it is fixable and not be an asshole? that would be greatly appreciated as well.

**Comment by Gibbu** [comment]
I mean, if you just read. It says:
![image](https://user-images.githubusercontent.com/20338746/118443034-c36cd400-b72e-11eb-93cb-ee1906d6917b.png)

Please use eyes.

**Comment by j-elmen** [comment]
Hello, I'm having the same issue but I'm not sure how this solves it. Could you explain what I have to do?
Hopefully this doesn't come off as too babyish, I just want to know where to start.
